
app: app.cpp client_communication_manager.cpp
	g++ -pthread app.cpp client_communication_manager.cpp -o app 
client_communication_manager.cpp:
	g++ -o app client_communication_manager.cpp
clean:
	rm app
