
app: app.cpp client_communication_manager.cpp
	g++ -pthread app.cpp client_communication_manager.cpp -std=gnu++11 -o app 
client_communication_manager.cpp:
	g++ -o app client_communication_manager.cpp -std=gnu++11
clean:
	rm app
