server: server.cpp server_communication_manager.cpp
	g++ -pthread server.cpp server_communication_manager.cpp -o server
server_communication_manager.cpp:
	g++ -o app server_communication_manager.cpp
clean:
	rm server
